target("thread")
    set_kind("static")
    add_files("src/**.c")
    set_configdir("src")
    add_configfiles("src/config.h.in")
    add_includedirs("src")
    add_defines("LCUI_THREAD_PTHREAD")
    add_syslinks("pthread", "dl")
